In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('sample_credit.csv')

In [5]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,...,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,5965.128713,-0.241768,0.281829,0.906164,0.263916,-0.046353,0.133134,-0.071791,-0.064802,0.802379,...,-0.051994,-0.152667,-0.033292,0.021271,0.087125,0.108154,0.005533,0.002912,63.020562,0.003800
std,4472.712504,1.521726,1.308149,1.159164,1.441120,1.182986,1.307373,1.077437,1.259125,1.155150,...,0.913856,0.631114,0.487832,0.594425,0.428188,0.562819,0.410886,0.266261,184.492872,0.061533
min,0.000000,-27.670569,-34.607649,-15.496222,-4.657545,-32.092129,-23.496714,-26.548144,-23.632502,-6.329801,...,-11.468435,-8.527145,-15.144340,-2.512377,-2.577363,-1.338556,-7.976100,-3.509250,0.000000,0.000000
25%,2072.500000,-1.013135,-0.208350,0.412752,-0.614489,-0.643510,-0.629975,-0.542363,-0.190784,0.071116,...,-0.268135,-0.549665,-0.174123,-0.327857,-0.158137,-0.328038,-0.084479,-0.015753,5.000000,0.000000
50%,4563.000000,-0.372624,0.288381,0.944342,0.219852,-0.152524,-0.152621,-0.055776,0.012791,0.805293,...,-0.123286,-0.136735,-0.045811,0.079956,0.120865,0.042879,-0.004566,0.015893,15.950000,0.000000
75%,10231.500000,1.150869,0.901632,1.602707,1.125501,0.371301,0.505448,0.476175,0.274582,1.506342,...,0.032715,0.247521,0.081546,0.410798,0.359081,0.476792,0.120836,0.077184,50.890000,0.000000
max,15010.000000,1.960497,8.636214,4.101716,10.463020,34.099309,21.393069,34.303177,5.060381,10.392889,...,22.588989,4.534454,13.876221,3.200201,5.525093,3.517346,8.254376,4.860769,7712.430000,1.000000

In [22]:
def best_corr(args):
    temp= []
    for i,v in enumerate(args):
        if v<1.0:
            temp.append((i,v))
    temp = sorted(temp ,key=lambda x:x[1])
    idx, corrv = temp[-1]
    return (df.columns[idx],corrv)
        
df.corr().apply(best_corr)

Time           (V13, 0.517629889638993)
V1           (V25, 0.22996334901096543)
V2         (Class, 0.16663033721295434)
V3           (V22, 0.27329779322897857)
V4         (Class, 0.22948751937596687)
V5            (V15, 0.1174370759116171)
V6        (Amount, 0.22074583076826376)
V7        (Amount, 0.32716969870081736)
V8            (V1, 0.22989228130013153)
V9           (Time, 0.4700983725351354)
V10           (V3, 0.15008142008396147)
V11          (Time, 0.3762062279983042)
V12          (V15, 0.17143980062002273)
V13           (Time, 0.517629889638993)
V14           (Time, 0.408843579160902)
V15          (V12, 0.17143980062002273)
V16          (V14, 0.31090031528722056)
V17           (V14, 0.3466709877744654)
V18          (V16, 0.22939124905957597)
V19          (V18, 0.12335887790774584)
V20         (Amount, 0.220921174839262)
V21           (V2, 0.14615304957632333)
V22           (V3, 0.27329779322897857)
V23          (V21, 0.14238653522991268)
V24         (V10, 0.039946024178469264)
V25           (V1, 0.22996334901096543)
V26           (Time, 0.316185916578899)
V27           (V28, 0.2906407824020363)
V28           (V27, 0.2906407824020363)
Amount        (V7, 0.32716969870081736)
Class        (V11, 0.29723145185305483)
dtype: object